version: '3.8'
services:
  db:
    image: postgres:16
    container_name: chess-pgsql
    restart: always
    environment:
      POSTGRES_DB: onlinechess
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chess-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build: .
    container_name: chess-app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redisdata:

